export const FAKE_PROFILES = [
    {
        firstName: 'Александр',
        lastName: 'Гончаров',
        middleName: 'Викторович',
        bio: 'Опытный строитель с многолетним стажем.',
        birth: '1975-02-15',
        photo: null,
        starsCount: 5,
        reviewsCount: 9,
        competitionLevel: 3,
        competitionPoints: 1200,
    },
    {
        firstName: 'Максим',
        lastName: 'Беспалов',
        middleName: 'Петрович',
        bio: 'Специалист по отделке квартир.',
        birth: '1990-08-23',
        photo: null,
        starsCount: 4,
        reviewsCount: 6,
        competitionLevel: 2,
        competitionPoints: 3000,
    },
    {
        firstName: 'Дмитрий',
        lastName: 'Кузнецов',
        middleName: 'Александрович',
        bio: 'Новичок в строительстве, готов к новым вызовам.',
        birth: '2002-05-10',
        photo: null,
        starsCount: 3,
        reviewsCount: 4,
        competitionLevel: 1,
        competitionPoints: 500,
    },
    {
        firstName: 'Сергей',
        lastName: 'Чернов',
        middleName: 'Сергеевич',
        bio: 'Мастер по укладке плитки с пятилетним стажем.',
        birth: '1988-11-05',
        photo: null,
        starsCount: 5,
        reviewsCount: 8,
        competitionLevel: 4,
        competitionPoints: 7500,
    },
    {
        firstName: 'Андрей',
        lastName: 'Захаров',
        middleName: 'Игоревич',
        bio: 'Молодой специалист в области строительства.',
        birth: '1995-03-22',
        photo: null,
        starsCount: 4,
        reviewsCount: 5,
        competitionLevel: 2,
        competitionPoints: 2000,
    },
    {
        firstName: 'Юрий',
        lastName: 'Карасев',
        middleName: 'Иванович',
        bio: 'Профессионал в монтаже окон.',
        birth: '1982-09-14',
        photo: null,
        starsCount: 4,
        reviewsCount: 7,
        competitionLevel: 3,
        competitionPoints: 5600,
    },
    {
        firstName: 'Олег',
        lastName: 'Трофимов',
        middleName: 'Андреевич',
        bio: 'Специалист по внутренней отделке.',
        birth: '1985-06-07',
        photo: null,
        starsCount: 3,
        reviewsCount: 5,
        competitionLevel: 2,
        competitionPoints: 4000,
    },
    {
        firstName: 'Владислав',
        lastName: 'Сидоров',
        middleName: 'Павлович',
        bio: 'Имею опыт работы с различными материалами.',
        birth: '1998-02-19',
        photo: null,
        starsCount: 4,
        reviewsCount: 6,
        competitionLevel: 3,
        competitionPoints: 6500,
    },
    {
        firstName: 'Евгений',
        lastName: 'Романов',
        middleName: 'Владимирович',
        bio: 'Талантливый строитель, специализирующийся на каркасных домах.',
        birth: '1978-12-30',
        photo: null,
        starsCount: 5,
        reviewsCount: 10,
        competitionLevel: 5,
        competitionPoints: 14500,
    },
    {
        firstName: 'Виктор',
        lastName: 'Сергеев',
        middleName: 'Николаевич',
        bio: 'Новичок в сфере ремонта, стремлюсь к развитию.',
        birth: '2004-04-25',
        photo: null,
        starsCount: 2,
        reviewsCount: 3,
        competitionLevel: 1,
        competitionPoints: 800,
    },

    // ADMIN
    {
        firstName: 'Шустов',
        lastName: 'Владимир',
        photo: null,
    },
] as const;
